services:
  - type: web
    name: stickynotes
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: false
    startCommand: ./render-init.sh
    envVars:
      - key: TMPDIR
        value: /tmp/plik
    healthCheckPath: /config
    buildCommand: ./build-for-render.sh
    staticPublishPath: ./webapp
    headers:
      - path: "/*.js"
        name: "Content-Type"
        value: "application/javascript"
      - path: "/*.css"
        name: "Content-Type"
        value: "text/css" 