services:
  - type: web
    name: plik-sticky-notes
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: false
    startCommand: ./render-init.sh
    envVars:
      - key: NGINX_LOG_PATH
        value: /tmp/nginx-logs
      - key: TMPDIR
        value: /tmp
      - key: PORT
        value: 80
    healthCheckPath: /
    buildCommand: ./build-for-render.sh
    staticPublishPath: ./webapp
    headers:
      - path: "/*.js"
        name: "Content-Type"
        value: "application/javascript"
      - path: "/*.css"
        name: "Content-Type"
        value: "text/css" 