name: build

on:
  push:
    branches:
      - master

jobs:  
  test:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'root-gg' }}
    steps:
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Fetch tags
      run: |
        git fetch --prune --unshallow --tags

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Run
      run: make release-and-push-to-docker-hub